title: Creating interactive vizualizations for media analysis
description: >-
  Learn how to create web based interactive visualizations of different kinds of
  media analysis to help you discover new potential from your content.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
